[book]
authors = ["Christophe Rosset"]
language = "en"
multilingual = false
src = "src"
title = "Toolchain Notes"
description = "The notes I've taken while diving into the source code of rolldown and oxc"

[output.html]
git-repository-url = "https://github.com/topheman/toolchain-notes"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/topheman/toolchain-notes/edit/master/{path}"
site-url = "/toolchain-notes/"
no-section-label = false
additional-css = ["mdbook-custom.css"]

[output.html.redirect]
"/napi/README.html" = "../napi/index.html"
"/oxc/README.html" = "../oxc/index.html"
"/oxc-resolver/README.html" = "../oxc-resolver/index.html"
"/rolldown/README.html" = "../rolldown/index.html"
"/rust/README.html" = "../rust/index.html"
