[book]
authors = ["Christophe Rosset"]
language = "en"
multilingual = false
src = "src"
title = "Toolchain Notes"

[output.html]
git-repository-url = "https://github.com/topheman/toolchain-notes"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/topheman/toolchain-notes/edit/master/{path}"
site-url = "/toolchain-notes/"
